version: "3.8"

services:
  postgres:
    build: ./db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bar_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: ./bar_spring
    restart: always
    container_name: backend
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    volumes:
      - ./bar_spring:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bar_db?stringtype=unspecified
      - SPRING_FLYWAY_ENABLED=false
  #    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
  frontend:
    build: ./bar_frontend
    container_name: frontend
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - /app/node_modules
      - ./bar_frontend:/app

volumes:
  postgres-data:
