services:
#  bar_postgres:
#    build: ./db
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: ${PASSWORD}
#      POSTGRES_DB: bar_db
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#  bar_redis:
#    container_name: bar_redis
#    image: redis:latest
#    ports:
#      - "6380:6380"
#    environment:
#      REDIS_PASSWORD: ${PASSWORD}
#    restart: always
#  bar_rabbitmq:
#    container_name: bar_rabbitmq
#    image: rabbitmq:latest
#    ports:
#      - "5672:5672"
#      - "15673:15672"
#    environment:
#      RABBITMQ_USER: ${USERNAME}
#      RABBITMQ_PASSWORD: ${PASSWORD}
#    restart: always

  bar_backend:
    build: ./bar_backend
    restart: always
    container_name: bar_backend
    networks:
      - app_network
    ports:
      - "8080:8080"
#    volumes:
#      - ./bar_backend:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bar_db
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - GBYZZZ_URL_TO_VALIDATE=http://baruserenable:8081/validate
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:29092
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="aa132435aa";
      - GBYZZZ_APP_JWT=${JWT_KEY}
      - GBYZZZ_APP_JWT_EXPIRATION=${JWT_EXPIRATION}
      - APP_MINIO_ENDPOINT=http://minio:9000
      - APP_MINIO_USERNAME=${USER}
      - APP_MINIO_PASSWORD=${PASSWORD}
      - APP_MINIO_USERPICBUCKET=user-pic-bucket
      - APP_MINIO_COCKTAILIMAGE=cocktail-image
      - APP_MINIO_COCKTAILTHUMBNAIL=cocktail-thumbnail

  bar_frontend:
    build: ./bar_frontend
    container_name: bar_frontend
    restart: always
    networks:
      - app_network
    ports:
      - "443:443"
#    volumes:
#      - /app/node_modules
#      - ./bar_frontend:/app

  bar_user_enable:
    build: ./bar_user_enable
    restart: always
    container_name: baruserenable
    networks:
      - app_network
    working_dir: /app
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:29092
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="aa132435aa";

  bar_email:
    build: ./bar_email
    restart: always
    container_name: bar_email
    networks:
      - app_network
    ports:
      - "8082:8082"
    working_dir: /app
    environment:
      - GBYZZZ_RECOVER_URL=https://localhost:443/recover_password
      - SPRING_MAIL_HOST=${MAIL_HOST}
      - SPRING_MAIL_PORT=${MAIL_PORT}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:29092
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="aa132435aa";

  bar_search:
    build: ./bar_search
    restart: always
    container_name: bar_search
    networks:
      - app_network
    ports:
      - "8083:8083"
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bar_db?stringtype=unspecified
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_USERNAME=${USER}
      - SPRING_ELASTICSEARCH_PASSWORD=${PASSWORD}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=kafka:29092
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="aa132435aa";

networks:
  app_network:
    external: true
#volumes:
#  postgres-data:
