version: "3.8"

services:
#  bar_postgres:
#    build: ./db
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: ${PASSWORD}
#      POSTGRES_DB: bar_db
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#  bar_redis:
#    container_name: bar_redis
#    image: redis:latest
#    ports:
#      - "6380:6380"
#    environment:
#      REDIS_PASSWORD: ${PASSWORD}
#    restart: always
#  bar_rabbitmq:
#    container_name: bar_rabbitmq
#    image: rabbitmq:latest
#    ports:
#      - "5672:5672"
#      - "15673:15672"
#    environment:
#      RABBITMQ_USER: ${USERNAME}
#      RABBITMQ_PASSWORD: ${PASSWORD}
#    restart: always

  bar_backend:
    build: ./bar_backend
    restart: always
    container_name: bar_backend
    depends_on:
      - "bar_postgres"
      - "bar_redis"
      - "bar_rabbitmq"
    ports:
      - "8080:8080"
#    volumes:
#      - ./bar_backend:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/bar_db?stringtype=unspecified
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - GBYZZZ_URL_TO_VALIDATE=http://baruserenable:8081/validate
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_DATA_REDIS_HOST=localhost
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_STREAM_USER=${USERNAME}
      - SPRING_RABBITMQ_STREAM_PASSWORD=${PASSWORD}
      - GBYZZZ_APP_JWT=${JWT_KEY}
      - GBYZZZ_APP_JWT_EXPIRATION=${JWT_EXPIRATION}

  bar_frontend:
    build: ./bar_frontend
    container_name: bar_frontend
    restart: always
    ports:
      - "443:443"
#    volumes:
#      - /app/node_modules
#      - ./bar_frontend:/app

  bar_user_enable:
    build: ./bar_user_enable
    restart: always
    container_name: baruserenable
    depends_on:
      - "bar_redis"
      - "bar_rabbitmq"
    ports:
      - "8081:8081"
    working_dir: /app
    environment:
      - SPRING_DATA_REDIS_HOST=localhost
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_STREAM_USER=${USERNAME}
      - SPRING_RABBITMQ_STREAM_PASSWORD=${PASSWORD}

  bar_email:
    build: ./bar_email
    restart: always
    container_name: bar_email
    depends_on:
      - "bar_rabbitmq"
    ports:
      - "8082:8082"
    working_dir: /app
    environment:
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_STREAM_USER=${USERNAME}
      - SPRING_RABBITMQ_STREAM_PASSWORD=${PASSWORD}
      - GBYZZZ_RECOVER_URL=http://localhost:7777/recover_password
      - SPRING_MAIL_HOST=${MAIL_HOST}
      - SPRING_MAIL_PORT=${MAIL_PORT}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}

#volumes:
#  postgres-data:
