apiVersion: v1
kind: Service
metadata:
    name: bar-redis
spec:
  selector:
    app.kubernetes.io/name: bar-redis
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: bar-rabbitmq
spec:
  selector:
    app.kubernetes.io/name: bar-rabbitmq
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379