apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar_backend_deployment
  labels:
    app: bar_backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bar_backend
  template:
    metadata:
      labels:
        app: bar_backend
    spec:
      containers:
        - name: bar_backend
          image: gbyzzz/gbyzzz_repository:bar_web_app_backend
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://barpostgres:5432/bar_db?stringtype=unspecified"
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: GBYZZZ_URL_TO_VALIDATE
              value: "http://baruserenable:8081/validate"
            - name: SPRING_DATA_REDIS_HOST
              value: "bar_redis"
            - name: SPRING_RABBITMQ_HOST
              value: "bar_rabbitmq"